### ISSUE TITLE
[SSR] Error transforming app.vue: Cannot read properties of undefined (reading 'uid')

### ISSUE THREAD

**Issue by lewebsimple** [nuxt/framework#2599]
I've been getting strange warnings tonight on fresh Nuxt3 projects, both on OSX and Linux.
The warnings look like the following:
```
 WARN  [SSR] Error transforming .../testing/app.vue: Cannot read properties of undefined (reading 'uid')                                                      

  at Object.statSync (node_modules/graceful-fs/polyfills.js:313:17)
  at isDirectory (node_modules/resolve/lib/sync.js:22:23)
  at loadNodeModulesSync (node_modules/resolve/lib/sync.js:191:17)
  at Function.resolveSync [as sync] (node_modules/resolve/lib/sync.js:98:17)
  at resolveFrom$3 (node_modules/vite/dist/node/chunks/dep-76613303.js:3911:29)
  at resolvePackageData (node_modules/vite/dist/node/chunks/dep-76613303.js:30046:19)
  at node_modules/vite/dist/node/chunks/dep-76613303.js:30426:15
  at Array.find (<anonymous>)
  at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-76613303.js:30425:44)
  at Context.resolveId (node_modules/vite/dist/node/chunks/dep-76613303.js:30257:28)
```

Running `npx nuxi info` gives the following:
```
- Operating System: `Darwin`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```
I get the same error on Linux with Node v14.

Any ideas ?!

**Comment by liasica** [comment]
Same problem here

**Comment by g30ffr3ll1n** [comment]
Same problem here
OS: Windows 10
Node Version: v16.13.1
Nuxt Version: v3.0.0-27338323.1e98259  
Package Manager: Yarn @ 1.22.17
Bundler: Vite

**Comment by Kunie-dev** [comment]
Same problem

OS: Windows 10
Node Version: v16.13.1
Nuxt Version: v3.0.0-27338323.1e98259
Package Manager: NPM @ 8.1.2
Bundler: Vite

**Comment by SteveEdson** [comment]
Me too in a Github actions task:

<details>
<summary>Stack trace</summary>
<pre><code>#15 [builder 6/6] RUN npm run build
#15 0.427 
#15 0.427 > build
#15 0.427 > nuxt build
#15 0.427 
#15 0.509 Nuxt CLI v3.0.0-27338323.1e98259
#15 3.719 ℹ Vite warmed up in 57ms
#15 3.737 
#15 3.737  ERROR  [vite:resolve] Cannot read properties of undefined (reading 'uid')
#15 3.737 
#15 3.737 
#15 3.737  ERROR  Cannot read properties of undefined (reading 'uid')
#15 3.737 
#15 3.737   at Object.statSync (node_modules/graceful-fs/polyfills.js:313:17)
#15 3.737   at isDirectory (node_modules/resolve/lib/sync.js:22:23)
#15 3.737   at loadNodeModulesSync (node_modules/resolve/lib/sync.js:191:17)
#15 3.737   at Function.resolveSync [as sync] (node_modules/resolve/lib/sync.js:98:17)
#15 3.737   at resolveFrom$3 (node_modules/vite/dist/node/chunks/dep-76613303.js:3911:29)
#15 3.737   at resolvePackageData (node_modules/vite/dist/node/chunks/dep-76613303.js:30046:19)
#15 3.737   at node_modules/vite/dist/node/chunks/dep-76613303.js:30426:15
#15 3.737   at Array.find (<anonymous>)
#15 3.737   at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-76613303.js:30425:44)
#15 3.737   at Object.resolveId (node_modules/vite/dist/node/chunks/dep-76613303.js:30257:28)
#15 3.737 
#15 ERROR: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
------
 > [builder 6/6] RUN npm run build:
#15 3.737   at isDirectory (node_modules/resolve/lib/sync.js:22:23)
#15 3.737   at loadNodeModulesSync (node_modules/resolve/lib/sync.js:191:17)
#15 3.737   at Function.resolveSync [as sync] (node_modules/resolve/lib/sync.js:98:17)
#15 3.737   at resolveFrom$3 (node_modules/vite/dist/node/chunks/dep-76613303.js:3911:29)
#15 3.737   at resolvePackageData (node_modules/vite/dist/node/chunks/dep-76613303.js:30046:19)
#15 3.737   at node_modules/vite/dist/node/chunks/dep-76613303.js:30426:15
#15 3.737   at Array.find (<anonymous>)
#15 3.737   at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-76613303.js:30425:44)
#15 3.737   at Object.resolveId (node_modules/vite/dist/node/chunks/dep-76613303.js:30257:28)
#15 3.737 </code></pre>
</details>

**Comment by newbeea** [comment]
same here when using yarn or npm
pnpm works, but the .output/server/index.mjs can't run seperately: "Cannot find package 'unenv'"

**Comment by soufiene-slimi** [comment]
It looks like it's a dependency bug, I get it to work by copying the `package-lock.json` from [stackblitz.com](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=package-lock.json) and re-run the npm install command, this should get you running to test the nuxt3 😄

**Comment by Lycoon** [comment]
Same issue following the same steps with these specs.
Seems related to #2601 

- Operating System: `Windows 10`
- Node Version: `v16.13.1`
- Nuxt Version: `3.0.0-27338323.1e98259`
- Package Manager: `npm@8.3.0`
- Bundler: `Vite`

**Comment by arpadev13** [comment]
i think it's a dependecy bug ... so you can copy [SB Starter Package-lock.json](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=package-lock.json) and then try `npm install` or `yarn install` *make sure your npm or yarn is the latest version*. hope it works ❤️

**Comment by danielroe** [comment]
For now, you can work around this by adding a resolution for resolve in your `package.json`:
```json
{
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "nuxt3": "latest"
  },
  "resolutions": {
    "resolve": "1.20.0"
  }
}
```

**Comment by newbeea** [comment]
> I find this work around at the same time, thanks anyway.

**Comment by SunMar** [comment]
@danielroe what other steps are needed to make this workaround work? I am working with a brand new initialized nuxt 3 project, updated my `package.json` file and tried running `npm update`, `npm install`, removing `package-lock.json`. but I'm still experiencing the error.

**Comment by danielroe** [comment]
@SunMar `resolutions` only works for yarn. For npm v8, you can replace `resolutions` with `overrides`.

**Comment by gldkru** [comment]
```
[worker] Cannot find package 'unenv' imported from /.../.nuxt/nitro/index.mjs 15:47:17
Did you mean to import unenv@0.4.3/node_modules/unenv/runtime/polyfill/fetch.node.cjs?
```

My Error, after `pnpm update` and `pnpm i`

**Comment by danielroe** [comment]
@gldkru That doesn't seem like a related issue, as [we're not fully compatible with pnpm yet](https://github.com/nuxt/framework/discussions/939). Was it working beforehand?

**Comment by Kzai** [comment]
This issue occurred for me when switching node versions with nvm.

**Comment by gldkru** [comment]
Updated config:
```
nvm use 16.13.1
yarn cache clean
yarn install
yarn dev
```

Errors remains:
```
 WARN  [SSR] Error transforming /Users/user/.../node_modules/nuxt3/dist/app/nuxt.mjs: Cannot read properties of undefined (reading 'uid')                                                             16:09:50

  at Object.statSync (node_modules/graceful-fs/polyfills.js:313:17)
  at isDirectory (node_modules/resolve/lib/sync.js:22:23)
  at loadNodeModulesSync (node_modules/resolve/lib/sync.js:191:17)
  at Function.resolveSync [as sync] (node_modules/resolve/lib/sync.js:98:17)
  at resolveFrom$3 (node_modules/vite/dist/node/chunks/dep-76613303.js:3911:29)
  at resolvePackageData (node_modules/vite/dist/node/chunks/dep-76613303.js:30046:19)
  at node_modules/vite/dist/node/chunks/dep-76613303.js:30426:15
  at Array.find (<anonymous>)
  at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-76613303.js:30425:44)
  at Context.resolveId (node_modules/vite/dist/node/chunks/dep-76613303.js:30257:28)
```

**Comment by gldkru** [comment]
> ```json
> "resolutions": {
>     "resolve": "1.20.0"
>   }
> ```

It's work for me! Thank you :)

**Comment by SunMar** [comment]
Changing `resolutions` to `overrides` didn't work for me (using npm 8 and node 16), but using yarn did solve the problem. Will use yarn for now until this gets fixed in a future build. Thanks for the workaround @danielroe !

**Comment by leechuanfeng** [comment]
> For now, you can work around this by adding a resolution for resolve in your `package.json`:
> 
> ```json
> {
>   "private": true,
>   "scripts": {
>     "dev": "nuxi dev",
>     "build": "nuxi build",
>     "start": "node .output/server/index.mjs"
>   },
>   "devDependencies": {
>     "nuxt3": "latest"
>   },
>   "resolutions": {
>     "resolve": "1.20.0"
>   }
> }
> ```

This works for me, after amending my "nuxt3" to "latest" and adding the "resolutions": { "resolve": "1.20.0" }, I ran `yarn install` again and it's working.

**Comment by danielroe** [comment]
The underlying issue is https://github.com/isaacs/node-graceful-fs/issues/221 (triggered by https://github.com/browserify/resolve/commit/1382486e2c1063393f6e6856f2e68330e67a7bc5).

It will be closed by https://github.com/isaacs/node-graceful-fs/pull/220 though this PR seems not to be progressing at the moment, so we may need to find other solutions.

**Comment by howbizarre** [comment]
> > ```json
> > "resolutions": {
> >     "resolve": "1.20.0"
> >   }
> > ```
> 
> It's work for me! Thank you :)

Works only with **YARN** manager - for NPM doesn't...

**Comment by peteromano** [comment]
For npm, just add resolve 1.20 to your dev deps (not overrides)

**Comment by howbizarre** [comment]
> For npm, just add resolve 1.20 to your dev deps (not overrides)

Cool... It works fine...

For NPM v8.x in package.json

`{
    ...
    "devDependencies": {
        "nuxt3": "latest",
        "resolve": "1.20.0"
    }
}`

**Comment by lewebsimple** [comment]
It appears the issue has been resolved with release 4.2.9 of node-graceful-fs !
See https://github.com/isaacs/node-graceful-fs/pull/220

**Comment by newbeea** [comment]
> 

use yarn or npm, pnpm only works on dev mode

**Comment by peteromano** [comment]
@lewebsimple Yea, not without a silly remark from isaacs though.

**Comment by Intevel** [comment]
I have still the same problem with the playground of Nuxt3 modules. 

```
"resolutions": {
    "resolve": "1.20.0"
  }
``` 
This doesn't work for me.

**Comment by vicasoo** [comment]
> 

Same problem here

**Comment by may820806** [comment]
same problem here.
