### ISSUE TITLE
crash on starting new initialised project on windows 11

### ISSUE THREAD

**Issue by ghostchan** [nuxt/framework#4256]
### Environment

Operating System: Windows 11
Node Version: v16.14.2
Nuxt Version: 3.0.0-27494471.1091d45
Package Manager: npm@8.5.0
Builder: vite
User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

npx nuxi init nuxt3-app
cd nuxt3-app
npm i
npm run dev

### Describe the bug

The server is crashing after start. Tried to re-initialise a new project but same error.

### Additional context

 ERROR  [worker reload] [worker init] Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

  at new NodeError (node:internal/errors:371:5)
  at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1035:11)
  at defaultResolve (node:internal/modules/esm/resolve:1105:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
  at link (node:internal/modules/esm/module_job:78:36)

**Comment by HoraceKeung** [comment]
Getting same error on Windows 10, Node Version: v16.14.2, Package Manager: npm@8.5.0

**Comment by danielroe** [comment]
This should _now_ be resolved in nitropack 0.2.3+. Would you try force upgrading via `npx nuxi upgrade --force`?

**Comment by mrauhu** [comment]
> This should _now_ be resolved in nitropack 0.2.3+. Would you try force upgrading via `npx nuxi upgrade --force`?

@danielroe unfortunately latest Nuxt 3 with `nitropack@0.2.4` is not working in monorepo.

<details>
  <summary>npm run build</summary>

```
> nuxt3-monorepo@0.0.0 build
> npm run -w packages/app build


> build
> nuxi build

Nuxt CLI v3.0.0-27495135.4d1a6ba                                                                              02:05:31
i Vite client warmed up in 2181ms                                                                             02:05:37
i Client built in 2188ms                                                                                      02:05:37
i Building server...                                                                                          02:05:37
√ Server built in 606ms                                                                                       02:05:38
√ Generated public .output/public                                                                       nitro 02:05:38
start Building server...                                                                                nitro 02:05:38

 WARN  '@nuxt/devalue' is imported by ../../node_modules/nuxt3/dist/core/runtime/nitro/renderer.mjs, but could not be resolved – treating it as an external dependency


 WARN  '@vue/shared' is imported by @vue/shared?commonjs-external, but could not be resolved – treating it as an external dependency


 WARN  '@vue/runtime-dom' is imported by @vue/runtime-dom?commonjs-external, but could not be resolved – treating it as an external dependency


 WARN  'vue-bundle-renderer' is imported by ../../node_modules/nuxt3/dist/core/runtime/nitro/renderer.mjs, but could not be resolved – treating it as an external dependency


 ERROR  Rollup error: Could not load vue/server-renderer (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open 'C:\Projects\nuxt3-monorepo\packages\app\vue\server-renderer'


 ERROR  Could not load vue/server-renderer (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open 'C:\Projects\nuxt3-monorepo\packages\app\vue\server-renderer'



npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @nuxt3-monorepo/app
npm ERR!   at location: C:\Projects\nuxt3-monorepo\packages\app
```

</details>

## Broken

* `nuxt3@3.0.0-27495135.4d1a6ba`
* `nitropack@0.2.4` 

```
npm ls nitropack
nuxt3-monorepo@0.0.0 C:\Projects\nuxt3-monorepo
`-- @nuxt3-monorepo/app@0.0.0 -> .\packages\app
  `-- nuxt3@3.0.0-27495135.4d1a6ba
    `-- nitropack@0.2.4
```

## Working

* `nuxt3@3.0.0-27488831.368610e`
* `nitropack@npm:nitropack-edge@0.2.3-27495133.b9271d7` 

```
npm ls nitropack
nuxt3-monorepo@0.0.0 C:\Projects\nuxt3-monorepo
`-- @nuxt3-monorepo/app@0.0.0 -> .\packages\app
  `-- nuxt3@3.0.0-27488831.368610e
    `-- nitropack@npm:nitropack-edge@0.2.3-27495133.b9271d7
```

**Comment by davidedisalvo** [comment]
I'm having the same problem. Tried to remove node modules and reinstalled them, and also run `npx nuxi upgrade --force`. 
Windows 10, Node Version: v16.14.2, Package Manager: npm@8.5.0

**Comment by ghostchan** [comment]
nuxt3@3.0.0-27495976.e31c604  works well

**Comment by markusgeert** [comment]
I'm still getting the original error on `Nuxt v3.0.0-27495976.e31c604` when trying to generate the default project (`nuxi init`) using `nuxi generate`. This is on windows 10, with nitropack `0.2.5`.

**Comment by FieldMarshallVague** [comment]
I'm on Windows 10.

My package.json has this: "nuxt3": "latest"

I can confirm that rimraf-ing the node_modules folder, 'npm i' and then 'npx nuxi upgrade --force' (just in case) worked for me to fix the OP error.

**Comment by ayZagen** [comment]
> nuxt3@3.0.0-27495976.e31c604 works well

later versions not working tried until  `3.0.0-27497374.59593a0`
