### ISSUE TITLE
'setupDevtoolsPlugin' is not exported by `unenv`

### ISSUE THREAD

**Issue by billymaulana** [nuxt/framework#4325]
### Environment

NUXT 3 : 3.0.0-27497374.59593a0
NODE : 16.4.2
pnpm": "^6.32.3"

### Reproduction

.

### Describe the bug

when normaly build its fine.
<img width="870" alt="image" src="https://user-images.githubusercontent.com/13347455/163191690-78da4ea7-0795-4496-b709-41b5a5c71664.png">

### Additional context
my nuxt config not set preset.
when im build NITRO_PRESET=cloudflare pnpm build. 

### Logs
Error like this:
```
 ERROR  Rollup error: 'setupDevtoolsPlugin' is not exported by node_modules/.pnpm/unenv@0.4.6/node_modules/unenv/runtime/mock/proxy.mjs, imported by node_modules/.pnpm/pinia@2.0.13_d3195e5b5ca92757b2890fe178df3bd1/node_modules/pinia/dist/pinia.mjs

 ERROR  'setupDevtoolsPlugin' is not exported by node_modules/.pnpm/unenv@0.4.6/node_modules/unenv/runtime/mock/proxy.mjs, imported by node_modules/.pnpm/pinia@2.0.13_d3195e5b5ca92757b2890fe178df3bd1/node_modules/pinia/dist/pinia.mjs

  at error (node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:1784:30)
  at Module.error (node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:12345:16)
  at Module.traceVariable (node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:12703:29)
  at ModuleScope.findVariable (node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:11333:39)
  at FunctionScope.findVariable (node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:6301:38)
  at ChildScope.findVariable (node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:6301:38)
  at Identifier.bind (node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:7592:40)
  at CallExpression.bind (node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:5166:23)
  at CallExpression.bind (node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:8774:15)
  at ExpressionStatement.bind (node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/es/shared/rollup.js:5166:23)
  

```
<img width="870" alt="image" src="https://user-images.githubusercontent.com/13347455/163189354-35be2a23-9dff-48ae-96ee-d2d026765762.png">

**Comment by danielroe** [comment]
would you provide a reproduction? 🙏

**Comment by billymaulana** [comment]
when im not set nitro preset: in my nuxt.config error. but in the documentation node-server its default preset.
finally im set in my nuxt config. 
```
nitro: {
      preset: 'node-server',
 },
```
and when build NITRO_PRESET=cloudflare pnpm build success.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/13347455/163217215-777c1fec-f08b-4cef-9c09-c2190ea4f9e2.png">

Now My problem is when wrangler publish to clodflare worker and this is a error:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/13347455/163217666-d76b78cd-8f9f-4196-96ff-a4119d6d036b.png">

build folder:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/13347455/163217788-26c1ceb9-e4e3-4601-8011-6ea77cf38238.png">

my wrangler.toml
<img width="301" alt="image" src="https://user-images.githubusercontent.com/13347455/163217879-1add2f5b-de63-4f9c-96ed-69fbfcb7c918.png">

**Comment by pi0** [comment]
This seems like an issue with pnpm and externals.

**Comment by aligzl** [comment]
any updates?

**Comment by jontybrook** [comment]
I am also seeing this with today's latest v3.0.0-27506609.eed7036 

![image](https://user-images.githubusercontent.com/542319/164120084-30a08bdf-d407-4baa-88c3-2fb324abe857.png)

**Comment by jontybrook** [comment]
> This seems like an issue with pnpm and externals. ([unjs/nitro#106](https://github.com/unjs/nitro/issues/106))

I'm using yarn v1.22.18 and also getting this; which indicates to me that it's not pnpm related.

**Comment by micheee** [comment]
For the sake of completeness: 
I am on yarn too — with the `service-worker`-Preset on `Nuxt CLI v3.0.0-rc.1` and seeing this as well.

**Comment by marshallswain** [comment]
@pi0 I've provided a reproduction in this issue: https://github.com/nuxt/framework/issues/4403

**Comment by marshallswain** [comment]
https://stackblitz.com/edit/github-8cjrqx?file=package.json

**Comment by cinob** [comment]
any updates?

**Comment by danielroe** [comment]
The cause is that pinia imports `setupDevtoolsPlugin` from `@vue/devtools-api`. We deliberately stub out vue devtools on the server. So rollup, in trying to inline this function, fails.

As a workaround, you can do:

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  alias: {
    '@vue/devtools-api': '@vue/devtools-api',
  },
  modules: ['@pinia/nuxt'],
})
```

**Comment by brandonratz** [comment]
@danielroe Thank you for the workaround.  Like previously mentioned, I am also using Yarn and not PnPM. My build steps are:
```
"build": "nuxi build",
"build_cloudflare": "NITRO_PRESET=cloudflare yarn build",
```

The errors prior to the alias workaround were:
```
 ERROR  Rollup error: 'setupDevtoolsPlugin' is not exported by node_modules/unenv/runtime/mock/proxy.mjs, imported by node_modules/pinia/dist/pinia.mjs


 ERROR  'setupDevtoolsPlugin' is not exported by node_modules/unenv/runtime/mock/proxy.mjs, imported by node_modules/pinia/dist/pinia.mjs
```

**Comment by marshallswain** [comment]
@danielroe does https://stackblitz.com/edit/github-8cjrqx?file=package.json serve as an adequate reproduction?  Or do we need a full repo?

**Comment by danielroe** [comment]
No need for further reproduction 👍

**Comment by igorbelikov** [comment]
@brandonratz upgrade your yarn version from 1 to 2

https://yarnpkg.com/getting-started/migration#step-by-step

>Run yarn `set version berry` to enable v2 (cf [Install](https://yarnpkg.com/getting-started/install) for more details)

**Comment by loremru** [comment]
Any news?

**Comment by ppodds** [comment]
Can be reproduced on 3.0.0 rc4

**Comment by huuhait** [comment]
same here
build good
but can't start server...

**Comment by acidjazz** [comment]
build is good - cant start server - a deps update takes down the environment

**Comment by maxbellec** [comment]
when i do the suggested change, the errors changes to `__VUE_PROD_DEVTOOLS__ is not defined`

```
[nuxt] [request error] __VUE_PROD_DEVTOOLS__ is not defined
  at Object.install (./.output/server/chunks/app/server.mjs:2996:13)  
  at Object.use (./.output/server/chunks/handlers/renderer.mjs:5786:29)  
  at ./.output/server/chunks/app/server.mjs:19030:18  
  at fn (./.output/server/chunks/app/server.mjs:3723:27)  
  at Object.callAsync (./.output/server/chunks/app/server.mjs:3484:19)  
  at callWithNuxt (./.output/server/chunks/app/server.mjs:3725:23)  
  at applyPlugin (./.output/server/chunks/app/server.mjs:3685:39)  
  at applyPlugins (./.output/server/chunks/app/server.mjs:3694:11)  
  at async createNuxtAppServer (./.output/server/chunks/app/server.mjs:19471:7)  
  at async Object.renderToString (./.output/server/chunks/handlers/renderer.mjs:270:19)
```

**Comment by dawidgola** [comment]
I have the same problem 

```
[nuxt] [request error] The requested module 'unenv/runtime/mock/proxy' does not provide an export named 'setupDevtoolsPlugin'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)  
  at async ./server/chunks/handlers/renderer.mjs:11152:24  
  at async ./server/chunks/handlers/renderer.mjs:11208:64  
  at async ./server/node_modules/h3/dist/index.mjs:420:19  
  at async Server.nodeHandler (./server/node_modules/h3/dist/index.mjs:370:7)
```
any solution  ?

**Comment by danielroe** [comment]
If you are not using pinia, then this can be caused by vue-router. You can try manually installing version 4.0.

**Comment by dawidgola** [comment]
@danielroe I have "vue-router": "^4.0.16" Do you think to use the older one ?

**Comment by dawidgola** [comment]
thanks, it works !

**Comment by danielroe** [comment]
It's not a bug in `vue-router`. It and `pinia` both import `@vue/devtools-api` for the purpose of client-side integration. But that's not something we want in our server code. It's code that will never be used, so we mock it out in nitro (unenv). Ideally it wouldn't be imported into the node code of either of them. But we can also stub it better.

We've pinned vue-router in future edge/RC releases until we resolve: https://github.com/nuxt/framework/pull/5767

**Comment by timmolter** [comment]
I'm getting the same error over and over in an infinite loop until an OOM occurs.

```
[nuxt] [request error] The requested module 'unenv/runtime/mock/proxy' does not provide an export named 'setupDevtoolsPlugin'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)  
  at ModuleJob.run (node:internal/modules/esm/module_job:194:5)  
  at async Promise.all (index 0)  
  at ESMLoader.import (node:internal/modules/esm/loader:409:24)  
  at ./node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs:15:24  
  at ./node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs:70:91  
  at ./.output/server/node_modules/h3/dist/index.mjs:420:19  
  at Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:370:7)
```

We tried pinning our vue-router to 4.0.16 via  `"vue-router": "~4.0.16"` in 'package.json', but it didn't help. 

What else could we try?

**Comment by timmolter** [comment]
BTW, as another hint, this problem doesn't occur on our Windows local dev machine, but only when we deploy remotely to Ubuntu 22 LTS.

**Comment by LoiLock** [comment]
Seems like this was fixed 2 hours ago

**Comment by pi0** [comment]
Should be fixed in RC.5. You can remove workarounds.

**Comment by tranthotuong** [comment]
![image](https://user-images.githubusercontent.com/50495846/183363979-0834b8ed-61bf-4973-a000-a55c40a285bf.png)
although, I using nuxt 3 RC5. But I have the same problem, so any solution?

**Comment by danielroe** [comment]
Would you ensure you can replicate after running `npx nuxi upgrade` and if so, open a new issue witha reproduction? 🙏

**Comment by tranthotuong** [comment]
> Would you ensure you can replicate after running `npx nuxi upgrade` and if so, open a new issue witha reproduction? 🙏

![image](https://user-images.githubusercontent.com/50495846/183375597-2ef619a5-b1fb-4093-8508-6d7553d6460d.png)
![image](https://user-images.githubusercontent.com/50495846/183375678-80052631-d9a6-4b95-9538-105cc2a1991a.png)
After I upgrade, Nuxt runs on ver v3.0.0.rc-6 and nuxi the same. But It is still an error.

**Comment by ma-jahn** [comment]
@danielroe 

I am experiencing the same after upgrading to nuxt rc8.
After checking the the dependencies linked above (vue-router and pinia) it now looks like it's caused by @nuxtjs/i18n.

Here is a small reproduction repo (Nuxt 3 RC8 + nuxt-i18n): https://stackblitz.com/edit/nuxt-starter-dyand4?file=package.json

**Comment by danielroe** [comment]
@ma-jahn I can't reproduce with that stackblitz - it seems to be working fine.

**Comment by ma-jahn** [comment]
Hi @danielroe 
Thanks for the quick response.

`npm run dev` (initial command) is working fine.
`npm run generate`is throwing the following:

```
 ERROR  [nuxt] [request error] [unhandled] [500] Named export 'setupDevtoolsPlugin' not found. The requested module 'file:///home/projects/nuxt-starter-dyand4/node_modules/unenv/runtime/mock/proxy.cjs' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'file:///home/projects/nuxt-starter-dyand4/node_modules/unenv/runtime/mock/proxy.cjs';
const { setupDevtoolsPlugin } = pkg;

  at async eval (./.nuxt/prerender/chunks/renderer.mjs:12918:24)  
  at async eval (./.nuxt/prerender/chunks/renderer.mjs:12972:64)  
  at async eval (./.nuxt/prerender/chunks/renderer.mjs:33:22)  
  at async eval (./node_modules/h3/dist/index.mjs:571:19)
```

Could not find how to change the default npm command within that stackblitz 🤷

**Comment by ma-jahn** [comment]
Just upgraded to `v3.0.0-rc.8-27679173.c688e18 ` and it's working!

@danielroe @pi0 Thank you so much for this blazing fast fix!

**Comment by Erica-lyj** [comment]
> The cause is that pinia imports `setupDevtoolsPlugin` from `@vue/devtools-api`. We deliberately stub out vue devtools on the server. So rollup, in trying to inline this function, fails.
> 
> As a workaround, you can do:
> 
> ```js
> import { defineNuxtConfig } from 'nuxt'
> 
> export default defineNuxtConfig({
>   alias: {
>     '@vue/devtools-api': '@vue/devtools-api',
>   },
>   modules: ['@pinia/nuxt'],
> })
> ```
i fail, but in this way success
```
  import { defineNuxtConfig } from 'nuxt'
  export default defineNuxtConfig({
    buildModules: ['@pinia/nuxt'],
    alias: {
      '@vue/devtools-api': '@vue/devtools-api',
    },
 })
```
i use npm
must execute the command
```
npm install pinia @pinia/nuxt @nuxtjs/composition-api --legacy-peer-deps
```

**Comment by danielroe** [comment]
You should definitely not install `@nuxtjs/composition-api` in a Nuxt 3 project. Make sure you are using the latest version of the pinia module.

**Comment by Erica-lyj** [comment]
> 

thanks, after I uninstalled @nuxtjs/composition-api, the packaging was still successful
