### ISSUE TITLE
rc.6 to rc.7    ERROR  Cannot start nuxt:  nuxtCtx.tryUse is not a function  

### ISSUE THREAD

**Issue by andysay** [nuxt/framework#6523]
### Environment

Nuxt project info:                                                                                                                                                                   09:35:07

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.7`
- Package Manager:  `npm@8.13.1`
- Builder:          `vite`
- User Config:      `modules`, `progress`, `sitemap`, `vue`, `runtimeConfig`, `css`, `buildModules`, `build`
- Runtime Modules:  `~/modules/sitemap`, `@nuxtjs/tailwindcss@5.3.1`, `nuxt-progress@0.1.6`
- Build Modules:    `@pinia/nuxt@0.4.0`
------------------------------

### Reproduction

-

### Describe the bug

rc.6 to rc.7    ERROR  Cannot start nuxt:  nuxtCtx.tryUse is not a function

**Comment by brunomendesfx** [comment]
fixed up #6516 

try remove node_modules and install again, in package.json

```
"nuxt": "npm:nuxt3@latest"
```

**Comment by shtse8** [comment]
> fixed up #6516
> 
> try remove node_modules and install again, in package.json
> 
> ```
> "nuxt": "npm:nuxt3@latest"
> ```

Another error  occur after adding this and reinstall node_modules
```
 ERROR  Nuxt Build Error: Named export 'createFilter' not found. The requested module 'vite' is a CommonJS module, which may not support all module.exports as named exports.                                                                                       00:39:54
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vite';
const { normalizePath: normalizePath$1, transformWithEsbuild, formatPostcssSourceMap, createFilter } = pkg;


  import { normalizePath as normalizePath$1, transformWithEsbuild, formatPostcssSourceMap, createFilter } from 'vite';
  ^^^^^^^^^^^^
  SyntaxError: Named export 'createFilter' not found. The requested module 'vite' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:

  import pkg from 'vite';
  const { normalizePath: normalizePath$1, transformWithEsbuild, formatPostcssSourceMap, createFilter } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
  at async bundle (node_modules/nuxt/dist/index.mjs:1864:76)
  at async build (node_modules/nuxt/dist/index.mjs:1840:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:41:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Zalexios** [comment]
pnpm update resolved the issue too

**Comment by viandwi24** [comment]
I'm still having the same problem, I've tried to remove node_modules and then reinstall, tried to update node, npm, yarn and the result is still the same error "Cannot start nuxt: nuxtCtx.tryUse is not a function".

trying to use nodes 16,17 and 18 doesn't work either.

is there something wrong?


```
Nuxt CLI v3.0.0-rc.7                                                                                          06:35:56
                                                                                                              06:36:04
  > Local:    http://localhost:3000/
  > Network:  http://172.28.2.119:3000/


 ERROR  Cannot start nuxt:  nuxtCtx.tryUse is not a function                                                  06:36:04

  at useNuxt (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:47:28)
  at extendViteConfig (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:772:16)
  at addVitePlugin (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:798:3)
  at initNuxt (node_modules/nuxt/dist/index.mjs:1441:3)
  at Object.ready (node_modules/nuxt/dist/index.mjs:1419:18)
  at load (node_modules/nuxi/dist/chunks/dev.mjs:6768:27)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6813:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)
```

```
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.7`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `css`, `plugins`, `build`, `modules`, `buildModules`, `experimental`, `components`, `vite`, `intlify`, `vueuse`, `windicss`, `content`
- Runtime Modules:  `nuxt-windicss@2.4.3`, `@intlify/nuxt3@0.2.3`, `@vueuse/nuxt@8.9.3`, `@nuxt/content@2.0.1`, `@pinia/nuxt@0.3.1`
- Build Modules:    `@nuxtjs/eslint-module@3.1.0`, `unplugin-icons/nuxt`, `@nuxtjs/svg@0.4.0`
```

**Comment by pi0** [comment]
@viandwi24 It seems you are using a dependency with older version. Please uce latest rc-8 and ensure to recreate lockfile. It should fix the problem.

**Comment by alee** [comment]
We were continuing to get this error until we explicitly added `@nuxt/kit-edge` dependency to our package.json - 

e.g.,

`"@nuxt/kit-edge": "^3.0.0-rc.8-27672245.2ec2d9b"`

We were also using the tailwindcss module which appears to pull in the wrong @nuxt/kit dep

**Comment by viandwi24** [comment]
> @viandwi24 It seems you are using a dependency with older version. Please uce latest rc-8 and ensure to recreate lockfile. It should fix the problem.


actually at first I used rc8 and experienced the same error.

and now it works, thanks for the reply, I realized too late to try to delete the lockfile too.

Previously I also tried to update using the nuxi upgrade command. is it possible that this mechanism for deleting temporary lockfiles can also be included in the nuxi upgrade command in the future?

**Comment by pi0** [comment]
@viandwi24 Yes it is. Nuxi will cleanup lock and node modules when you use --froce.

**Comment by molotow11** [comment]
Worked for me:
    "nuxt": "3.0.0-rc.8",
    "@nuxt/kit": "3.0.0-rc.8",

**Comment by max5432112345** [comment]
https://github.com/nuxt/framework/issues/6300#issuecomment-1205428147
