### ISSUE TITLE
sendRedirect() is encoding uri's that are already encoded

### ISSUE THREAD

**Issue by Hyperblaster** [nuxt/framework#7162]
### Environment

Using `aws-lambda` preset

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.4`
- Builder:          `vite`
- User Config:      `nitro`, `app`, `alias`, `css`, `hooks`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

Create a `/server/api/[...].ts` file with the following code, so we can proxy api requests from `ournuxturl.com/api` to `ouractualapi.com`

```

const baseURL = 'https://my.api.com';


import { createError, useBody, appendHeader } from 'h3';

export default defineEventHandler(async event => {

    const method = useMethod(event)
    const params = useQuery(event)
    const body = method !== 'GET' && method !== 'HEAD' ? await useBody(event) : undefined;
    var path = String(event.req.url).substring(4); //.split('/api').join('');
    let originalHeaders = event.req.headers; 

    let lookup = {
        'authorization': 1,
        'user-agent': 1,
        'accept': 1,
    }

    let headers = Object.keys(originalHeaders)
        .reduce(function(set, key) {
            if (!lookup[key]) {
                return set;
            }
            set[key] = originalHeaders[key];
            return set;
        }, {});

    let errorData;
    let response;

    try {
        response = await $fetch.raw(path, {
            headers,
            baseURL,
            method,
            params,
            body
        })
    } catch (error) {
        errorData = error.response._data;
        event.res.statusCode = errorData.statusCode || errorData.status;
        event.res.setHeader("Content-Type", 'application/json');
        event.res.end(JSON.stringify(errorData, null, 2));
        return errorData;
    }

    if(errorData) {
        return errorData;
    }

    // Check how we should proxy
    var fullPath = `${baseURL}${path}`;
    var redirectURL = response.url;

    if(fullPath != redirectURL) {


        console.log('Correct URL to redirect to is', redirectURL);
        return sendRedirect(event, redirectURL, 302)
    }
    
    for (const header of ['content-type', 'cache-control']) {
        if (response.headers.has(header)) {
            appendHeader(event, header, response.headers.get(header));
        }
    }

    return response._data;
})

### Describe the bug

When using sendRedirect() the url we are redirecting to is being encoded which is mangling the intended url if it it already an encoded uri.
this is a problem that was not occurring prior to updating nuxt recently. and is breaking things like AWS S3 SignedURLs as the signature is encoded.


An example url is something like this:
```
https://storage.s3.us-west-2.amazonaws.com/files/62e9eb262106f7f6ff16b52f/image.png?AWSAccessKeyId=AZIA5ZO5F4R6KA5PSG78&Expires=1662126522&Signature=cRyednjMGj1Jhzpw7LpHwKQBjNQ%3D&response-cache-control=no-cache&response-content-disposition=inline
```

### Additional context

_No response_

### Logs

_No response_

**Comment by pi0** [comment]
Hi @Hyperblaster Can you please try upgrading lockfile? There is a recent fix that should address this (https://github.com/unjs/h3/commit/04b432cf3e67675b6f4e7f3b74e95e475b8b5bfe)

**Comment by danielroe** [comment]
I believe that has been resolved in https://github.com/unjs/h3/commit/04b432cf3e67675b6f4e7f3b74e95e475b8b5bfe (h3 version 0.7.19). Would you try upgrading h3 to confirm?

**Comment by Hyperblaster** [comment]
@danielroe forgive me from being dumb. But i don't have unjs/h3 installed. just the following in my `package.json`

Isn't `unjs/h3` included within nuxt?

```
"devDependencies": {
    "nuxt": "3.0.0-rc.4",
    "sass": "^1.50.0",
    "sass-loader": "^12.6.0"
  },
  
  ```
  
  One of the concerns is that even though i have nuxt installed at `3.0.0-rc.4` it appears to be running `rc-8` i'm not sure if that's a versioning issue with recent releases?

**Comment by danielroe** [comment]
Yes, h3 is a sub-dependency, but you can upgrade it in several ways, perhaps by explicitly installing it or by running somthing like `yarn upgrade h3` or `npm upgrade h3`. And yes, there was a versioning issue, for versions below rc7. You can refer to https://github.com/nuxt/framework/discussions/6554.

**Comment by Hyperblaster** [comment]
@danielroe thanks for the confirmation. Manually installing h3 doesn't upgrade the instance of the package the nuxt uses, so the issue is still there in nuxt. Time to go and try a rollback to the version of nuxt that was working.

**Comment by Hyperblaster** [comment]
thanks @danielroe upgrading to rc9 has resolved my issue
