### ISSUE TITLE
head.addEntry is not a function

### ISSUE THREAD

**Issue by thegears** [nuxt/framework#8929]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@6.1.3`
------------------------------

### Reproduction

https://github.com/nuxt/framework/

### Describe the bug

When i run dev, giving this error

```
head.addEntry is not a function

at ./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8
at fn (./node_modules/nuxt/dist/app/nuxt.mjs:148:27)
at Object.callAsync (./node_modules/unctx/dist/index.mjs:49:19)
at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:150:23)
at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:94:29)
at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:104:11)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)
at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
```

**Comment by DomVit5** [comment]
Some problem, tried fresh install and got this error

**Comment by thegears** [comment]
> Some problem, tried fresh install and got this error. Nuxt 3.0.0-rc.13

I installed Nuxt 3.0.0-rc.10, now working. You can try

**Comment by gomorizsolt** [comment]
Same here

**Comment by KovacsRoli** [comment]
Same issue for me, tried a fresh install with node 18.0.0 and npm 8.6.0 on macOS and got the same issue for both Nuxt 3.0.0-rc.13 and Nuxt 3.0.0-rc.12. The Nuxt 3.0.0-rc.11 or lover versions work

**Comment by I-NOZex** [comment]
+1, fresh install, windows 10
also happens with nuxt3@latest ( 3.0.0-rc.14-27802701.2f53495 )

**Comment by treighmawaka** [comment]
Same here. Confimed on `rc12` and `rc13`. I'm trying to spin up a reproduction if possible. The strangest thing is that everything worked well with the exact same setup.

**Comment by vernaillen** [comment]
v1.0.0 of @vueuse/head was released 2 hours ago, so maybe that caused it?
https://github.com/vueuse/head/releases/tag/v1.0.0

I tried fixing @vueuse/head to version 0.9.8, but with no success yet

**Comment by piscis** [comment]
I can confirm this is caused by a upstream release of @vueuse/head and I was able to fix it pnpm by overwrite vueuse/head and set it to v1.0.0-rc.14 like so:

```json
....
"pnpm": {
    "overrides": {
      "@vueuse/head": "v1.0.0-rc.14"
    }
  }
...
```

**Comment by vernaillen** [comment]
@piscis  that worked for me too, thx

**Comment by quadrat-studio** [comment]
@piscis Worked for me too, thanks!

**Comment by AsuraLuo** [comment]
@piscis I fixed this issue by yarn or npm add resolutions in package.json, thanks
```javascript
 "resolutions": {
    "@vueuse/head": "v1.0.0-rc.14"
  }
```

**Comment by Aleksandr-Baranchuk** [comment]
> 

 that worked for me too, thx

**Comment by isimmons** [comment]
For npm resolutions didn't work but overrides does

```
 "overrides": {
    "@vueuse/head": "v1.0.0-rc.14"
  }
```

Then `npm install`

**Comment by ihornovelution** [comment]
Neither "resolutions" nor "overrides" helped me. Still getting "head.addEntry is not a function" error.

**Comment by localhousee** [comment]
> Neither "resolutions" nor "overrides" helped me. Still getting "head.addEntry is not a function" error.

Weird, im using override and error is gone

After edit `package.json` and `pnpm install --shamefully hoist`, my page back to normal

**Comment by owlnai** [comment]
For NPM, I had to delete `package-lock.json` because `npm` seem to ignore overrides when doing subsequent installs.

**Comment by treighmawaka** [comment]
> Neither "resolutions" nor "overrides" helped me. Still getting "head.addEntry is not a function" error.

For what it's worth, switching to `pnpm` worked for me.

In a nutshell, remove `node_modules` and `package-lock.json` and add the pnpm overrides:
```
  "pnpm": {
    "overrides": {
      "@vueuse/head": "v1.0.0-rc.14"
    }
  }
```

Run `pnpm install`

This should work.

**Comment by harlan-zw** [comment]
Have replied in the duplicate issue: https://github.com/nuxt/framework/issues/8936

Should be fixed, re-install and try again
