### ISSUE TITLE
Auto add `.nojekill` to `.output/public` on generate

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/framework#9898]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `-`
- Package Manager:  `npm@8.3.1`
- Builder:          `webpack`
- User Config:      `target`, `router`, `head`, `loading`, `css`, `plugins`, `components`, `buildModules`, `modules`, `toast`, `image`, `content`, `styleResources`, `eslint`, `stylelint`, `generate`, `build`
- Runtime Modules:  `@nuxtjs/svg@0.4.0`, `@nuxt/content@1.15.1`, `cookie-universal-nuxt@2.2.1`, `vue-toastification/nuxt`, `@nuxt/image@0.7.1`
- Build Modules:    `@nuxtjs/style-resources@1.2.1`, `@nuxtjs/eslint-module@3.1.0`, `@nuxtjs/stylelint-module@4.1.0`
------------------------------

### Reproduction

.

### Describe the bug

I've been trying all night to figure out why my deploy to Github Pages wasn't working.
Seems like Nuxt 3 does not add `.nojekyll` to `.output/public` automatically.
Nuxt 2 added it automatically to the `dist/` folder.

### Additional context

I see that it is added in `.nuxt/dist/client/.nojekyll` but I don't know what this folder is used for.
The documentation clearly state that the Github Pages directory is `.output/public`

**Comment by manniL** [comment]
I agree that this would be helpful, but maybe even more when having a dedicated Nitro Preset for GitHub Pages.

**Comment by pi0** [comment]
@manniL Seems a good idea. Do you mind opening upstream issues in nitro for `static` (base) and `github-pages` presets? It would be nice to auto adjust Nitro's behavior for static/generate/prerender targets.

**Comment by manniL** [comment]
> @manniL Seems a good idea. Do you mind opening upstream issues in nitro for `static` (base) and `github-pages` presets? It would be nice to auto adjust Nitro's behavior for static/generate/prerender targets.

Done!

**Comment by esoubiran-aneo** [comment]
Hello, is there a workaround ? I'm trying this (https://github.com/esoubiran-aneo/docus-deployment/blob/main/.github/workflows/deploy-docs.yml) but it doesn't work.

**Comment by mrleblanc101** [comment]
@esoubiran-aneo Create the `.nojekyll` file manually and place it in your `public/` folder

**Comment by esoubiran-aneo** [comment]
> @esoubiran-aneo Create the `.nojekyll` file manually and place it in your `public/` folder

I just try this but it's seems it doesn't work. But when I download artifact, I can see every files begenning with a ` _` or the `.nojekyll` file.

**Comment by esoubiran-aneo** [comment]
https://esoubiran-aneo.github.io/docus-deployment/ I try another workflow (https://github.com/esoubiran-aneo/docus-deployment/blob/main/.github/workflows/nuxtjs.yml) but still broken

**Comment by esoubiran-aneo** [comment]
Ohhh, I know, I forget the base url. Thanks to your fast reply.
